### ISSUE TITLE
Pretrained models

### ISSUE THREAD

**Issue by decent-engineer-decent-datascientist** [chengtan9907/SimVPv2#3]
Hey @chengtan9907, are there any pretrained models that you could share?
It'd help kickstart learning on newer datasets, as well as act as a stand in set of weights to build pipelines.

**Comment by Lupin1998** [comment]
Hi, @decent-engineer-decent-datascientist, thanks for your interest in SimVPv2. Since video prediction methods on some low-resolution datasets need tuning of network structures (e.g., SimVP might use different layers in different datasets), it might be not useful to load a pre-trained model for a new dataset. Therefore, we haven't provided trained models in SimVP in the past.

Currently, we are working on this project to add more benchmark results and video prediction datasets. We plan to release trained models and logs in the future in regard to the convenience of the community. Please watch our latest update. And we will inform you when we release the models.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
