### ISSUE TITLE
Questions about loss and model architecture

### ISSUE THREAD

**Issue by bb846** [chengtan9907/SimVPv2#8]
Dear Authors,

Thank you for your inspiring work. I have some questions regarding of the loss function and model architecture. 

1) MSE loss might produce blurry result. Would it help if I replace it with L1 Loss?

2) It is believed that vanilla 2D convolution does not suffice to catch spatial-temporal correlation while it seems your model handles this well. I couldn't find detailed explanation in your paper. Could you please explain it?

With kind regrads.

**Comment by chengtan9907** [comment]
1.  In my practice, replacing MSE with L1 loss is not a good solution because it may be hard to optimize. I have seen some papers using MSE+L1 loss, which seems to work well.
2. I would like to suggest you refer to our manuscript: SimVP: Towards Simple yet Powerful Spatiotemporal Predictive Learning. The most important component is the `Translator`. Using vanilla conv as the translator usually fails. IncepU translator focuses on multi-scale feature learning and thus has great ability in long-range modeling. Our new gSTA translator is inspired by large kernel convs, and models long-range interactions in a more efficient way.

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
